### ISSUE TITLE
main.py: commands list

### ISSUE THREAD

**Issue by dikhomenko** [bingooo1337/project-init2024#24]
**Список команд:**
**- hello:** Отримати вітання від бота та показати меню.
**- add-contact [name] [phone]:** Додати новий контакт з іменем та телефонним номером, обробка помилки без завершення програми.
**- delete-contact [name]:** Видалити весь запис контакта.
**- change-phone [name] [old phone] [new phone]:** Змінити телефонний номер для вказаного контакту, обробка помилки без завершення програми..
**- phone [name]:** Показати телефонний номер для вказаного контакту.
**- all-contacts:** Показати всі контакти в адресній книзі.
**- add-birthday [name] [birthdate]:** Додати дату народження для вказаного контакту,  обробка помилки без завершення програми.
**- show-birthday [name]:** Показати дату народження для вказаного контакту.
**- birthdays:** Показати дні народження, які відбудуться протягом 7 днів.
**- birthdays [days number]:** Показати дні народження, які відбудуться протягом вказаної кількості днів. [days number] - optional, 7 days by default.
**- add-email [name] [email]:** Додати імейл до вказаного контакту, regexp, обробка помилки без завершення програми.
**- show-email [name]:** Показати імейл для вказаного контакту.
**- change-email [name] [new email]:** Змінити імейл для вказаного контакту.
**- add-address [name]:** Додати адресу, str.
**- change-address [name]:** Змінити адресу для вказаного контакту.
**- show-address [name]:** Показати адресу для вказаного контакту.
**- add-note [title][text]:** Додати нотатку.
**- change-note [title][text]:** Змінити нотатку.
**- delete-note [title]:** Видалити нотатку.
**- all-notes:** Показати всі нотатки
**- add-tag [title][tag]:** Додати тег до нотатки.
**- show-note [title]:** Показати нотатку.
**- search-tag [tag]:** Показати нотатки по тегу.
**- close або exit:** Закрити програму.

**Comment by zapadlo7** [comment]
@dikhomenko потрібно парочку фіксиків для правки вище в командах та в функціях: 
перейменувати all в all-contacts
додать change-address

- add-address [name]: Додати адресу, str. , тут потрібно після name додати [address] щоб було add-address [name] [address]
- change-address [name]: Додать [address] , щоб було change-address [name] [address]

**Comment by zapadlo7** [comment]
- hello: Отримати вітання від бота та показати меню.

і тут я так розумію, теж мабуть підправить,бо меню показується до вводу hello, одразу після запуску программи а після вводу hello ми залишаємо How can I help you? як і було мабуть

**Comment by zapadlo7** [comment]
і ще мабуть потрібно додать команду
delete-tag [tag]: Видалити тег.
